### ISSUE TITLE
Angular 2 RC-1

### ISSUE THREAD

**Issue by jaroslawziolkowski** [axiskafi/angular2-laravel5#1]
Hey,
have you any update for RC-1 I have loading errors for RC-1, for beta it works well. I have no idea what is wrong, because in angular change log isn't features which could brake code.

**Comment by axiskafi** [comment]
hi,
i havent tried that, could you please provide me your package.json file. Then i might take an attempt to update it for RC-1.

Also you can troubleshoot the problem by following the thread, it seems a common problem and mostly solvable by node update and cache clean 

https://github.com/angular/angular/issues/8473

**Comment by jaroslawziolkowski** [comment]
Please look at the RC 1 example. There are different dependencies, also not required is  angular.dev.js file. 

I afraid that for RC required are many changes. My file is same like on angular.io "get started" section.

**Comment by axiskafi** [comment]
made a new commit with the update of Angular 2.0.0-rc.1
hope it will solve your issue now.

**Comment by jaroslawziolkowski** [comment]
@axiskafi thanks, you are right it works.
