### ISSUE TITLE
why didn't it automatically compile when i change app.component.ts?

### ISSUE THREAD

**Issue by KimChan2013** [axiskafi/angular2-laravel5#2]
done along with the steps but it didn't work unless if i restart the server
and the gulp watch..... "finished"in less than 1minute everytime.it seems not watching....

**Comment by axiskafi** [comment]
you have to open two terminals, one is for php artisan server and one is for gulp watch. it should automatically compile in any .ts file change you are not suppose to run gulp watch every time.

**Comment by KimChan2013** [comment]
oh it does work.thank u~ so strange it was because i was always openning 2 terminals yesterday.   but it success today ~~~

and by the way. i tried to use laravel with angular2 before but don;t know how to combine them(i even couldn't open the index page with them.)
would u mind introducing some about it? something like the file structure and how to combine angular page with laravel blade?
it's ok if u r busy for teaching me.

thx all the time ~

**Comment by axiskafi** [comment]
hi,
regarding laravel 5 with angular2, it will be very big thing to cover. in short the setup of gulpfile.js(in the root folder) that copied all the compiled thing in the public/js folder and rest i explained in my github note. But you will understand it more deeply when you start developing the project.
