### ISSUE TITLE
angular2-laravel5@1.0.0 postinstall: `typings install` - Windows_NT 6.2.9200

### ISSUE THREAD

**Issue by basherr** [axiskafi/angular2-laravel5#5]
I have clone the repo and tried `npm install` after `composer update` and get stuck with the belove error.

![npm install](https://cloud.githubusercontent.com/assets/10073316/19227486/9dd5e5b6-8ed3-11e6-8e45-afccf2c4e0c6.PNG)

**Comment by basherr** [comment]
Sorry for the issue but still expects to work as it's described.

**Comment by jondoe3000** [comment]
Hi. I had the same problem and when I run php artisan --serve=0 I got this:

![image](https://cloud.githubusercontent.com/assets/20893855/23161872/c75361ae-f7f9-11e6-9ae3-d53fe0fa9f09.png)

**Comment by jondoe3000** [comment]
Hi. I got the same error than basherr and when I tried to run php artisan serve --host:0 I got this:

![image](https://cloud.githubusercontent.com/assets/20893855/23162080/9cf0ea3e-f7fa-11e6-8c53-2dd0c5b79ca5.png)

I hope someone could help me.
