### ISSUE TITLE
templateURL instead of inline template

### ISSUE THREAD

**Issue by 1tbq** [axiskafi/angular2-laravel5#7]
I am just experimenting with the code here.. which folder i should put the html for the templateURL instead of template for the component .please guide me. thank you

**Comment by axiskafi** [comment]
this is not an issue, this is basic understanding :-), whatever
angular2-laravel5/resources/assets/typescript/ 
here you have to place all the typescript files but typescript will compile the js files in the public folder.

So it will be easy if you keep the html files in the public folder
templateUrl: 'appView/front.html',

your file structure will be inside the laravel root folder public/appView/front.html

**Comment by 1tbq** [comment]
Thanks very much I really appreciate your prompt reply
